[package]
name = "kobzar_env"
version = "0.1.0"
authors = ["Max Naumchyk <max.naumch@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
dummy = []

[dependencies]
smallvec = "1.4"
time = "0.2"
arrayvec = "0.5"
